# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tbourgeais/Documents/robot-5-nema-14/code/GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1052, 512)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(680, 460, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(830, 70, 201, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelX = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelX.setObjectName("labelX")
        self.verticalLayout.addWidget(self.labelX)
        self.spinnerX = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.spinnerX.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinnerX.setObjectName("spinnerX")
        self.verticalLayout.addWidget(self.spinnerX)
        self.labelY = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelY.setObjectName("labelY")
        self.verticalLayout.addWidget(self.labelY)
        self.spinnerY = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.spinnerY.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinnerY.setObjectName("spinnerY")
        self.verticalLayout.addWidget(self.spinnerY)
        self.labelZ = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelZ.setObjectName("labelZ")
        self.verticalLayout.addWidget(self.labelZ)
        self.spinnerZ = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.spinnerZ.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinnerZ.setObjectName("spinnerZ")
        self.verticalLayout.addWidget(self.spinnerZ)
        self.RobotPlot = QtWidgets.QWidget(Dialog)
        self.RobotPlot.setGeometry(QtCore.QRect(30, 40, 751, 441))
        self.RobotPlot.setObjectName("RobotPlot")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelX.setText(_translate("Dialog", "X"))
        self.labelY.setText(_translate("Dialog", "Y"))
        self.labelZ.setText(_translate("Dialog", "Z"))
